export const PERMISSIONS = {
  tenantView: 'tenant.view',
  tenantManage: 'tenant.manage',
  tenantCreate: 'tenant.create',
  userView: 'user.view',
  userManage: 'user.manage',
  roleView: 'role.view',
  roleManage: 'role.manage',
  instanceView: 'instance.view',
  instanceCreate: 'instance.create',
  instanceUpdate: 'instance.update',
  instanceDelete: 'instance.delete',
  instanceStart: 'instance.start',
  instanceStop: 'instance.stop',
  instanceRestart: 'instance.restart',
  configView: 'config.view',
  configEdit: 'config.edit',
  configValidate: 'config.validate',
  configPublish: 'config.publish',
  configRollback: 'config.rollback',
  configForcePublish: 'config.force_publish',
  nodeView: 'node.view',
  nodeApprove: 'node.approve',
  nodeReject: 'node.reject',
  nodeDetach: 'node.detach',
  secretView: 'secret.view',
  secretManage: 'secret.manage',
  skillView: 'skill.view',
  skillEnable: 'skill.enable',
  skillDisable: 'skill.disable',
  skillManage: 'skill.manage',
  skillReview: 'skill.review',
  alertView: 'alert.view',
  alertAck: 'alert.ack',
  alertResolve: 'alert.resolve',
  auditView: 'audit.view',
  monitorView: 'monitor.view',
  notificationView: 'notification.view',
  templateUse: 'template.use',
  templateManage: 'template.manage',
  platformSettingsView: 'platform.settings.view',
  platformSettingsManage: 'platform.settings.manage'
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

